### ISSUE TITLE
Phone.dial not work on Android 6.0+ if set prompt's value to false

### ISSUE THREAD

**Issue by teerasej** [msywensky/nativescript-phone#27]
I don't sure this is normal behavior or not. 

I use `phone.dial('xxxxxx', false)`. It works well on iOS. But for Android it just does nothing. I also noticed that even prompt's value set to false, iOS still pop up the confirmation dialog before make a call.

It works on Android when I set prompt's value to `true`. Android opened the phone intent and let user to confirm before make a call. 

At the moment, I understand that prompt's value is ignored by the latest version of both OS. Is it correct?

**Comment by bradmartin** [comment]
Is permissions issue for 6+. I have something in the works and will update soon.

**Comment by bradmartin** [comment]
Fixed with 1.3.0

**Comment by teerasej** [comment]
Not sure. But after update to 1.3.0. The false value still not work with Android 6.0+

**Comment by bradmartin** [comment]
The user will need to approve permission for this on Android 6+. There is a
new method to prompt the user. I docd it on the readme, I'll update the
definition later today. The API for this plugin needs some love for sure to
be a little more stable/consistent :)

**Comment by bradmartin** [comment]
https://github.com/msywensky/nativescript-phone#requestcallpermission-request-android-call_phone-permission - again we should improve the docs and need to update the definition, but using this method and having the user confirm the permission should then allow Android 6+ to dial without prompting.
